In [25]:
import pandas as pd
import numpy as np

# Load the file
df = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\glp1-project\data\glp1_medicare_2023.csv",
    low_memory=False
)

# First check — did it load?
print("Loaded successfully!")
print(f"Rows: {len(df):,}")
print(f"Columns: {df.shape[1]}")

Loaded successfully!
Rows: 315,333
Columns: 22

In [26]:
print(df.columns[5])

Prscrbr_State_FIPS

In [27]:
print(df.columns.tolist())

['Prscrbr_NPI', 'Prscrbr_Last_Org_Name', 'Prscrbr_First_Name', 'Prscrbr_City', 'Prscrbr_State_Abrvtn', 'Prscrbr_State_FIPS', 'Prscrbr_Type', 'Prscrbr_Type_Src', 'Brnd_Name', 'Gnrc_Name', 'Tot_Clms', 'Tot_30day_Fills', 'Tot_Day_Suply', 'Tot_Drug_Cst', 'Tot_Benes', 'GE65_Sprsn_Flag', 'GE65_Tot_Clms', 'GE65_Tot_30day_Fills', 'GE65_Tot_Drug_Cst', 'GE65_Tot_Day_Suply', 'GE65_Bene_Sprsn_Flag', 'GE65_Tot_Benes']

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315333 entries, 0 to 315332
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Prscrbr_NPI            315333 non-null  int64
 1   Prscrbr_Last_Org_Name  315333 non-null  object
 2   Prscrbr_First_Name     315333 non-null  object
 3   Prscrbr_City           315333 non-null  object
 4   Prscrbr_State_Abrvtn   315333 non-null  object
 5   Prscrbr_State_FIPS     315333 non-null  object
 6   Prscrbr_Type           315333 non-null  object
 7   Prscrbr_Type_Src       315333 non-null  object
 8   Brnd_Name              315333 non-null  object
 9   Gnrc_Name              315333 non-null  object
 10  Tot_Clms               315333 non-null  int64
 11  Tot_30day_Fills        315333 non-null  float64
 12  Tot_Day_Suply          315333 non-null  int64
 13  Tot_Drug_Cst           315333 non-null  float64
 14  Tot_Benes              85793 non-null   float64
 15  GE65_Sprsn_Flag        140856 non-null  object
 16  GE65_Tot_Clms          174477 non-null  float64
 17  GE65_Tot_30day_Fills   174477 non-null  float64
 18  GE65_Tot_Drug_Cst      174477 non-null  float64
 19  GE65_Tot_Day_Suply     174477 non-null  float64
 20  GE65_Bene_Sprsn_Flag   300282 non-null  object
 21  GE65_Tot_Benes         15051 non-null   float64
dtypes: float64(8), int64(3), object(11)
memory usage: 52.9+ MB

In [29]:
df.head()

,Prscrbr_NPI,Prscrbr_Last_Org_Name,Prscrbr_First_Name,Prscrbr_City,Prscrbr_State_Abrvtn,Prscrbr_State_FIPS,Prscrbr_Type,Prscrbr_Type_Src,Brnd_Name,Gnrc_Name,...,Tot_Day_Suply,Tot_Drug_Cst,Tot_Benes,GE65_Sprsn_Flag,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,GE65_Tot_Day_Suply,GE65_Bene_Sprsn_Flag,GE65_Tot_Benes
0,1003004201,Philbrick,Natalie,Corpus Christi,TX,48,Internal Medicine,Claim-Specialty,Mounjaro,Tirzepatide,...,2424,93639.68,14.0,NaN,35.0,37.0,39630.53,1048.0,*,NaN
1,1003006552,Quinonez,Alner,Fort Meade,FL,12,Family Practice,Claim-Specialty,Mounjaro,Tirzepatide,...,628,24580.86,NaN,NaN,22.0,22.0,24580.86,628.0,*,NaN
2,1003006610,Rule,Cindi,Ireton,IA,19,Nurse Practitioner,Claim-Specialty,Mounjaro,Tirzepatide,...,308,12082.42,NaN,*,NaN,NaN,NaN,NaN,*,NaN
3,1003007048,Fereidouni,Sam,Scottsdale,AZ,04,Family Practice,Claim-Specialty,Mounjaro,Tirzepatide,...,6013,230779.06,36.0,NaN,163.0,186.3,205063.82,5307.0,#,NaN
4,1003007170,Danciu,Sorin,Chicago,IL,17,Cardiology,Claim-Specialty,Mounjaro,Tirzepatide,...,1166,44905.52,12.0,NaN,21.0,27.5,30247.42,790.0,*,NaN

In [30]:
# Keep only the columns you'll actually use for analysis
df = df[[
    'Prscrbr_NPI',
    'Prscrbr_State_Abrvtn',
    'Prscrbr_Type',
    'Brnd_Name',
    'Gnrc_Name',
    'Tot_Clms',
    'Tot_Drug_Cst',
    'Tot_Benes'
]]

print("After cleanup:")
print(f"Rows: {len(df):,}")
print(f"Columns: {df.shape[1]}")
print(df.columns.tolist())

After cleanup:
Rows: 315,333
Columns: 8
['Prscrbr_NPI', 'Prscrbr_State_Abrvtn', 'Prscrbr_Type', 'Brnd_Name', 'Gnrc_Name', 'Tot_Clms', 'Tot_Drug_Cst', 'Tot_Benes']

In [31]:
df.describe()

        Prscrbr_NPI       Tot_Clms  Tot_Drug_Cst     Tot_Benes
count  3.153330e+05  315333.000000  3.153330e+05  85793.000000
mean   1.498681e+09      42.952285  5.804171e+04     22.588871
std    2.881080e+08      56.868678  8.103552e+04     18.744292
min    1.003001e+09      11.000000  2.723710e+03     11.000000
25%    1.245682e+09      16.000000  2.083454e+04     13.000000
50%    1.497826e+09      26.000000  3.435997e+04     16.000000
75%    1.740766e+09      47.000000  6.332540e+04     25.000000
max    1.993000e+09    3227.000000  4.128824e+06    618.000000

In [32]:
unique_prescribers = df['Prscrbr_NPI'].nunique()
total_rows = len(df)

print(f"Total rows: {total_rows:,}")
print(f"Unique prescribers: {unique_prescribers:,}")
print(f"Avg brands per prescriber: {total_rows / unique_prescribers:.2f}")

Total rows: 315,333
Unique prescribers: 169,404
Avg brands per prescriber: 1.86

In [33]:
# How many brands does each prescriber use?
brands_per_doctor = df.groupby('Prscrbr_NPI')['Brnd_Name'].nunique()

# Distribution
print("Number of doctors prescribing X different brands:")
print(brands_per_doctor.value_counts().sort_index())

print("\nAs percentages:")
print((brands_per_doctor.value_counts(normalize=True).sort_index() * 100).round(1))

Number of doctors prescribing X different brands:
Brnd_Name
1    74238
2    54728
3    30113
4    10325
Name: count, dtype: int64

As percentages:
Brnd_Name
1    43.8
2    32.3
3    17.8
4     6.1
Name: proportion, dtype: float64

In [34]:
# Brand-level summary
brand_summary = df.groupby('Brnd_Name').agg(
    total_claims=('Tot_Clms', 'sum'),
    total_cost=('Tot_Drug_Cst', 'sum'),
    unique_prescribers=('Prscrbr_NPI', 'nunique'),
    avg_claims_per_prescriber=('Tot_Clms', 'mean')
).sort_values('total_claims', ascending=False)

# Add a market share column (% of total claims)
brand_summary['market_share_pct'] = (
    brand_summary['total_claims'] / brand_summary['total_claims'].sum() * 100
).round(1)

# Add cost per claim
brand_summary['avg_cost_per_claim'] = (
    brand_summary['total_cost'] / brand_summary['total_claims']
).round(2)

print(brand_summary)

           total_claims    total_cost  unique_prescribers  \
Brnd_Name
Ozempic         6416007  8.535566e+09              131910
Trulicity       4851616  6.666365e+09              109569
Mounjaro        1521598  1.965517e+09               44382
Rybelsus         755052  1.135017e+09               29472

           avg_claims_per_prescriber  market_share_pct  avg_cost_per_claim
Brnd_Name
Ozempic                    48.639277              47.4             1330.35
Trulicity                  44.279094              35.8             1374.05
Mounjaro                   34.284124              11.2             1291.75
Rybelsus                   25.619300               5.6             1503.23

In [35]:
specialty_summary = df.groupby('Prscrbr_Type').agg(
    total_claims=('Tot_Clms', 'sum'),
    unique_prescribers=('Prscrbr_NPI', 'nunique')
).sort_values('total_claims', ascending=False).head(15)

specialty_summary['claims_share_pct'] = (
    specialty_summary['total_claims'] / specialty_summary['total_claims'].sum() * 100
).round(1)

print(specialty_summary)

                                                    total_claims  \
Prscrbr_Type
Family Practice                                          3887473
Internal Medicine                                        3428583
Nurse Practitioner                                       2719125
Endocrinology                                            1912056
Physician Assistant                                       913376
General Practice                                          136178
Cardiology                                                102879
Pharmacist                                                 57094
Nephrology                                                 55764
Emergency Medicine                                         41360
Geriatric Medicine                                         41273
Hospitalist                                                34308
Student in an Organized Health Care Education/T...         29724
Pediatric Medicine                                         21423
General Surgery                                            16263

                                                    unique_prescribers  \
Prscrbr_Type
Family Practice                                                  55451
Internal Medicine                                                40185
Nurse Practitioner                                               41636
Endocrinology                                                     5710
Physician Assistant                                              14164
General Practice                                                  2066
Cardiology                                                        1530
Pharmacist                                                         811
Nephrology                                                         796
Emergency Medicine                                                 595
Geriatric Medicine                                                 684
Hospitalist                                                        678
Student in an Organized Health Care Education/T...                1529
Pediatric Medicine                                                 386
General Surgery                                                    293

                                                    claims_share_pct
Prscrbr_Type
Family Practice                                                 29.0
Internal Medicine                                               25.6
Nurse Practitioner                                              20.3
Endocrinology                                                   14.3
Physician Assistant                                              6.8
General Practice                                                 1.0
Cardiology                                                       0.8
Pharmacist                                                       0.4
Nephrology                                                       0.4
Emergency Medicine                                               0.3
Geriatric Medicine                                               0.3
Hospitalist                                                      0.3
Student in an Organized Health Care Education/T...               0.2
Pediatric Medicine                                               0.2
General Surgery                                                  0.1

In [36]:
state_summary = df.groupby('Prscrbr_State_Abrvtn').agg(
    total_claims=('Tot_Clms', 'sum'),
    unique_prescribers=('Prscrbr_NPI', 'nunique')
).sort_values('total_claims', ascending=False).head(15)

state_summary['claims_share_pct'] = (
    state_summary['total_claims'] / state_summary['total_claims'].sum() * 100
).round(1)

print(state_summary)

                      total_claims  unique_prescribers  claims_share_pct
Prscrbr_State_Abrvtn
TX                         1139364               12763              12.7
CA                         1098550               14840              12.3
NY                          965464               10833              10.8
FL                          859664               11050               9.6
PA                          658692                7789               7.3
NC                          554610                6475               6.2
OH                          529383                6792               5.9
MI                          478679                6184               5.3
GA                          475399                4775               5.3
IL                          408510                5572               4.6
TN                          381982                4241               4.3
IN                          358347                3977               4.0
AL                          356128                2798               4.0
MA                          354201                4481               4.0
LA                          343517                2918               3.8

In [37]:
df_2022 = pd.read_csv("C:/Users/ADMIN/Desktop/glp1-project/data/glp1_medicare_2022.csv", low_memory=False)

print("2022 loaded successfully!")
print(f"Rows: {len(df_2022):,}")
print(f"Columns: {df_2022.shape[1]}")
print(f"Unique prescribers: {df_2022['Prscrbr_NPI'].nunique():,}")
print(f"\nBrand breakdown:")
print(df_2022['Brnd_Name'].value_counts())

2022 loaded successfully!
Rows: 187,475
Columns: 22
Unique prescribers: 123,584

Brand breakdown:
Brnd_Name
Trulicity    95389
Ozempic      71639
Rybelsus     18413
Mounjaro      2034
Name: count, dtype: int64

In [38]:
# ── 2022 brand shares ──────────────────────────────────────
brand_2022 = df_2022.groupby('Brnd_Name').agg(
    total_claims_2022=('Tot_Clms', 'sum'),
    prescribers_2022=('Prscrbr_NPI', 'nunique')
)
brand_2022['share_2022'] = (
    brand_2022['total_claims_2022'] /
    brand_2022['total_claims_2022'].sum() * 100
).round(1)

# ── 2023 brand shares ──────────────────────────────────────
brand_2023 = df.groupby('Brnd_Name').agg(
    total_claims_2023=('Tot_Clms', 'sum'),
    prescribers_2023=('Prscrbr_NPI', 'nunique')
)
brand_2023['share_2023'] = (
    brand_2023['total_claims_2023'] /
    brand_2023['total_claims_2023'].sum() * 100
).round(1)

# ── Combine into one table ─────────────────────────────────
comparison = brand_2022[['share_2022', 'total_claims_2022', 'prescribers_2022']].join(
    brand_2023[['share_2023', 'total_claims_2023', 'prescribers_2023']],
    how='outer'
).fillna(0)

# ── Add change columns ─────────────────────────────────────
comparison['share_change'] = (
    comparison['share_2023'] - comparison['share_2022']
).round(1)

comparison['prescriber_growth'] = (
    comparison['prescribers_2023'] - comparison['prescribers_2022']
).astype(int)

comparison = comparison.sort_values('share_2023', ascending=False)

# ── Print brand level table ────────────────────────────────
print("=" * 65)
print("BRAND LEVEL: YEAR-OVER-YEAR SHARE SHIFT 2022 → 2023")
print("=" * 65)
print(comparison[[
    'share_2022',
    'share_2023',
    'share_change',
    'prescribers_2022',
    'prescribers_2023',
    'prescriber_growth'
]])

# ── Print company level totals ─────────────────────────────
print("\n" + "=" * 65)
print("COMPANY LEVEL: NOVO vs LILLY")
print("=" * 65)

novo_2022 = comparison.loc[['Ozempic','Rybelsus'], 'share_2022'].sum().round(1)
novo_2023 = comparison.loc[['Ozempic','Rybelsus'], 'share_2023'].sum().round(1)
lilly_2022 = comparison.loc[['Trulicity','Mounjaro'], 'share_2022'].sum().round(1)
lilly_2023 = comparison.loc[['Trulicity','Mounjaro'], 'share_2023'].sum().round(1)

print(f"Novo  2022: {novo_2022}%  →  2023: {novo_2023}%  (change: {round(novo_2023-novo_2022,1):+}pp)")
print(f"Lilly 2022: {lilly_2022}%  →  2023: {lilly_2023}%  (change: {round(lilly_2023-lilly_2022,1):+}pp)")

# ── The hypothesis test ────────────────────────────────────
print("\n" + "=" * 65)
print("HYPOTHESIS TEST")
print("=" * 65)

mounjaro_gain = comparison.loc['Mounjaro', 'share_change']
ozempic_change = comparison.loc['Ozempic', 'share_change']
trulicity_change = comparison.loc['Trulicity', 'share_change']

print(f"Mounjaro gained:    {mounjaro_gain:+.1f} percentage points")
print(f"Ozempic changed:    {ozempic_change:+.1f} percentage points")
print(f"Trulicity changed:  {trulicity_change:+.1f} percentage points")
print()

if abs(ozempic_change) > abs(trulicity_change):
    print("VERDICT: Mounjaro drew more share from OZEMPIC than Trulicity")
    print("→ Hypothesis CONFIRMED: Direct threat to Novo's franchise")
elif abs(trulicity_change) > abs(ozempic_change):
    print("VERDICT: Mounjaro drew more share from TRULICITY than Ozempic")
    print("→ Hypothesis WRONG: Primarily Lilly self-cannibalization")
else:
    print("VERDICT: Mixed — Mounjaro drew equally from both brands")
    print("→ Hypothesis PARTIALLY confirmed")

=================================================================
BRAND LEVEL: YEAR-OVER-YEAR SHARE SHIFT 2022 → 2023
=================================================================
           share_2022  share_2023  share_change  prescribers_2022  \
Brnd_Name
Ozempic          38.9        47.4           8.5             71639
Trulicity        54.6        35.8         -18.8             95389
Mounjaro          0.5        11.2          10.7              2034
Rybelsus          6.0         5.6          -0.4             18413

           prescribers_2023  prescriber_growth
Brnd_Name
Ozempic              131910              60271
Trulicity            109569              14180
Mounjaro              44382              42348
Rybelsus              29472              11059

=================================================================
COMPANY LEVEL: NOVO vs LILLY
=================================================================
Novo  2022: 44.9%  →  2023: 53.0%  (change: +8.1pp)
Lilly 2022: 55.1%  →  2023: 47.0%  (change: -8.1pp)

=================================================================
HYPOTHESIS TEST
=================================================================
Mounjaro gained:    +10.7 percentage points
Ozempic changed:    +8.5 percentage points
Trulicity changed:  -18.8 percentage points

VERDICT: Mounjaro drew more share from TRULICITY than Ozempic
→ Hypothesis WRONG: Primarily Lilly self-cannibalization

In [39]:
# ─────────────────────────────────────────────────────────────
# STEP 1: Build deciles for BOTH years separately
# ─────────────────────────────────────────────────────────────

# 2022 deciles
prescriber_volume_2022 = df_2022.groupby('Prscrbr_NPI')['Tot_Clms'].sum().reset_index()
prescriber_volume_2022.columns = ['Prscrbr_NPI', 'total_glp1_claims']
prescriber_volume_2022['decile'] = pd.qcut(
    prescriber_volume_2022['total_glp1_claims'],
    q=10,
    labels=range(1, 11),
    duplicates='drop'
)

# 2023 deciles (you already built this — recreating for clarity)
prescriber_volume_2023 = df.groupby('Prscrbr_NPI')['Tot_Clms'].sum().reset_index()
prescriber_volume_2023.columns = ['Prscrbr_NPI', 'total_glp1_claims']
prescriber_volume_2023['decile'] = pd.qcut(
    prescriber_volume_2023['total_glp1_claims'],
    q=10,
    labels=range(1, 11),
    duplicates='drop'
)

# ─────────────────────────────────────────────────────────────
# STEP 2: Add company labels
# ─────────────────────────────────────────────────────────────
def assign_company(brand):
    if brand in ['Ozempic', 'Rybelsus']:
        return 'Novo'
    elif brand in ['Trulicity', 'Mounjaro']:
        return 'Lilly'
    else:
        return 'Other'

df['Company'] = df['Brnd_Name'].apply(assign_company)
df_2022['Company'] = df_2022['Brnd_Name'].apply(assign_company)

# ─────────────────────────────────────────────────────────────
# STEP 3: Merge decile labels into both dataframes
# ─────────────────────────────────────────────────────────────
df_2022_d = df_2022.merge(
    prescriber_volume_2022[['Prscrbr_NPI', 'decile']],
    on='Prscrbr_NPI',
    how='left'
)

df_2023_d = df.merge(
    prescriber_volume_2023[['Prscrbr_NPI', 'decile']],
    on='Prscrbr_NPI',
    how='left'
)

# ─────────────────────────────────────────────────────────────
# STEP 4: Compute Novo share per decile, both years
# ─────────────────────────────────────────────────────────────
def company_share_by_decile(dframe, year_label):
    by_decile_company = dframe.groupby(
        ['decile', 'Company'],
        observed=True
    )['Tot_Clms'].sum().reset_index()
    
    pivoted = by_decile_company.pivot(
        index='decile',
        columns='Company',
        values='Tot_Clms'
    ).fillna(0)
    
    pivoted['total'] = pivoted['Novo'] + pivoted['Lilly']
    pivoted[f'novo_share_{year_label}'] = (pivoted['Novo'] / pivoted['total'] * 100).round(1)
    pivoted[f'lilly_share_{year_label}'] = (pivoted['Lilly'] / pivoted['total'] * 100).round(1)
    
    return pivoted[[f'novo_share_{year_label}', f'lilly_share_{year_label}']]

share_2022 = company_share_by_decile(df_2022_d, '2022')
share_2023 = company_share_by_decile(df_2023_d, '2023')

# ─────────────────────────────────────────────────────────────
# STEP 5: Build the comparison table
# ─────────────────────────────────────────────────────────────
decile_company_comparison = share_2022.join(share_2023)

decile_company_comparison['novo_share_change'] = (
    decile_company_comparison['novo_share_2023'] -
    decile_company_comparison['novo_share_2022']
).round(1)

decile_company_comparison['lilly_share_change'] = (
    decile_company_comparison['lilly_share_2023'] -
    decile_company_comparison['lilly_share_2022']
).round(1)

print("=" * 75)
print("NOVO vs LILLY: SHARE BY DECILE, 2022 → 2023")
print("=" * 75)
print(decile_company_comparison.to_string())

# ─────────────────────────────────────────────────────────────
# STEP 6: Headline read
# ─────────────────────────────────────────────────────────────
print("\n" + "=" * 75)
print("READ: WHERE DID NOVO WIN, AND BY HOW MUCH?")
print("=" * 75)

for decile in range(1, 11):
    change = decile_company_comparison.loc[decile, 'novo_share_change']
    if change > 0:
        verdict = "Novo gained"
    elif change < 0:
        verdict = "Novo LOST"
    else:
        verdict = "No change"
    print(f"  Decile {decile:2d}: {verdict} {abs(change)}pp")

===========================================================================
NOVO vs LILLY: SHARE BY DECILE, 2022 → 2023
===========================================================================
Company  novo_share_2022  lilly_share_2022  novo_share_2023  lilly_share_2023  novo_share_change  lilly_share_change
decile
1                   41.8              58.2             55.2              44.8               13.4               -13.4
2                   39.8              60.2             59.0              41.0               19.2               -19.2
3                   37.7              62.3             58.9              41.1               21.2               -21.2
4                   38.1              61.9             57.4              42.6               19.3               -19.3
5                   40.8              59.2             56.2              43.8               15.4               -15.4
6                   41.4              58.6             55.3              44.7               13.9               -13.9
7                   42.6              57.4             54.3              45.7               11.7               -11.7
8                   44.3              55.7             52.9              47.1                8.6                -8.6
9                   45.2              54.8             52.0              48.0                6.8                -6.8
10                  47.8              52.2             51.2              48.8                3.4                -3.4

===========================================================================
READ: WHERE DID NOVO WIN, AND BY HOW MUCH?
===========================================================================
  Decile  1: Novo gained 13.4pp
  Decile  2: Novo gained 19.2pp
  Decile  3: Novo gained 21.2pp
  Decile  4: Novo gained 19.3pp
  Decile  5: Novo gained 15.4pp
  Decile  6: Novo gained 13.9pp
  Decile  7: Novo gained 11.7pp
  Decile  8: Novo gained 8.6pp
  Decile  9: Novo gained 6.8pp
  Decile 10: Novo gained 3.4pp

In [40]:
# ─────────────────────────────────────────────────────────────
# BULLET 3: Brand share within each decile (2023)
# ─────────────────────────────────────────────────────────────

# Sum claims per (decile, brand)
decile_brand = df_2023_d.groupby(
    ['decile', 'Brnd_Name'],
    observed=True
)['Tot_Clms'].sum().reset_index()

# Total claims per decile (denominator for within-decile share)
decile_brand['decile_total'] = decile_brand.groupby(
    'decile',
    observed=True
)['Tot_Clms'].transform('sum')

# Within-decile brand share
decile_brand['brand_share_pct'] = (
    decile_brand['Tot_Clms'] /
    decile_brand['decile_total'] * 100
).round(1)

# Pivot for readability
decile_pivot = decile_brand.pivot(
    index='decile',
    columns='Brnd_Name',
    values='brand_share_pct'
).fillna(0)

decile_pivot = decile_pivot[['Ozempic', 'Trulicity', 'Mounjaro', 'Rybelsus']]

print("BRAND SHARE WITHIN EACH DECILE — 2023")
print("=" * 65)
print(decile_pivot.to_string())

BRAND SHARE WITHIN EACH DECILE — 2023
=================================================================
Brnd_Name  Ozempic  Trulicity  Mounjaro  Rybelsus
decile
1             49.7       38.2       6.6       5.5
2             55.1       36.2       4.9       3.8
3             55.4       36.6       4.5       3.4
4             52.7       36.8       5.8       4.7
5             51.4       37.2       6.6       4.8
6             50.2       37.2       7.5       5.1
7             48.7       37.1       8.6       5.6
8             47.1       37.0      10.1       5.8
9             45.8       36.1      11.9       6.2
10            45.5       34.5      14.2       5.7

In [41]:
# ─────────────────────────────────────────────────────────────
# BULLET 4: Decile structure within each major specialty (2023)
# ─────────────────────────────────────────────────────────────

# Get per-prescriber total volume + their primary specialty
# (Each doctor has one specialty in this data)
prescriber_with_specialty = df.groupby(
    ['Prscrbr_NPI', 'Prscrbr_Type']
)['Tot_Clms'].sum().reset_index()
prescriber_with_specialty.columns = ['Prscrbr_NPI', 'Specialty', 'total_glp1_claims']

# Focus on the top 5 specialties (96% of volume)
top_5_specialties = [
    'Family Practice',
    'Internal Medicine',
    'Nurse Practitioner',
    'Endocrinology',
    'Physician Assistant'
]

prescriber_top5 = prescriber_with_specialty[
    prescriber_with_specialty['Specialty'].isin(top_5_specialties)
].copy()

# Build separate deciles within each specialty
prescriber_top5['within_specialty_decile'] = prescriber_top5.groupby(
    'Specialty'
)['total_glp1_claims'].transform(
    lambda x: pd.qcut(x, q=10, labels=range(1, 11), duplicates='drop')
)

# Show decile cutoffs per specialty
print("DECILE CUTOFFS BY SPECIALTY (2023)")
print("=" * 75)

for spec in top_5_specialties:
    spec_data = prescriber_top5[prescriber_top5['Specialty'] == spec]
    
    decile_stats = spec_data.groupby('within_specialty_decile', observed=True).agg(
        prescribers=('Prscrbr_NPI', 'count'),
        min_claims=('total_glp1_claims', 'min'),
        max_claims=('total_glp1_claims', 'max'),
        avg_claims=('total_glp1_claims', 'mean')
    ).round(1)
    
    print(f"\n{spec}")
    print("-" * 75)
    print(decile_stats.to_string())

DECILE CUTOFFS BY SPECIALTY (2023)
===========================================================================

Family Practice
---------------------------------------------------------------------------
                         prescribers  min_claims  max_claims  avg_claims
within_specialty_decile
1                               6518          11          14        12.3
2                               4858          15          19        16.8
3                               5516          20          27        23.5
4                               5404          28          36        31.8
5                               5513          37          47        41.8
6                               5651          48          61        54.2
7                               5501          62          79        69.9
8                               5464          80         105        91.6
9                               5492         106         152       126.1
10                              5534         153        1311       236.6

Internal Medicine
---------------------------------------------------------------------------
                         prescribers  min_claims  max_claims  avg_claims
within_specialty_decile
1                               4400          11          14        12.4
2                               3985          15          21        17.6
3                               3962          22          30        25.9
4                               4047          31          41        35.9
5                               3858          42          54        47.7
6                               4028          55          71        62.7
7                               3976          72          93        81.9
8                               3930          94         126       108.7
9                               4011         127         186       152.0
10                              3988         187        5832       315.2

Nurse Practitioner
---------------------------------------------------------------------------
                         prescribers  min_claims  max_claims  avg_claims
within_specialty_decile
1                               5490          11          13        11.9
2                               3497          14          16        14.9
3                               3811          17          21        18.8
4                               4311          22          28        24.9
5                               4023          29          36        32.3
6                               3860          37          46        41.3
7                               4215          47          61        53.6
8                               4199          62          85        72.6
9                               4111          86         136       107.0
10                              4119         137        1876       282.4

Endocrinology
---------------------------------------------------------------------------
                         prescribers  min_claims  max_claims  avg_claims
within_specialty_decile
1                                575          11          46        25.8
2                                568          47          93        69.9
3                                573          94         145       119.2
4                                572         146         200       173.4
5                                568         201         261       229.6
6                                576         262         323       292.8
7                                570         324         399       360.7
8                                569         400         513       455.0
9                                568         514         692       589.5
10                               571         693        6704      1036.2

Physician Assistant
---------------------------------------------------------------------------
                         prescribers  min_claims  max_claims  avg_claims
within_specialty_decile
1                               1718          11          13        11.9
2                               1419          14          17        15.4
3                               1239          18          22        19.8
4                               1449          23          29        25.8
5                               1352          30          37        33.2
6                               1402          38          48        42.8
7                               1409          49          63        55.4
8                               1365          64          86        74.0
9                               1409          87         134       106.2
10                              1402         135        1963       267.8

In [42]:
# ─────────────────────────────────────────────────────────────
# PRESSURE TEST 1: Build 2022 brand-by-decile pivot for comparison
# ─────────────────────────────────────────────────────────────

# Step 1a: Sum claims per (decile, brand) for 2022
decile_brand_2022 = df_2022_d.groupby(
    ['decile', 'Brnd_Name'],
    observed=True
)['Tot_Clms'].sum().reset_index()

# Step 1b: Total claims per decile (denominator for within-decile share)
decile_brand_2022['decile_total'] = decile_brand_2022.groupby(
    'decile',
    observed=True
)['Tot_Clms'].transform('sum')

# Step 1c: Within-decile brand share
decile_brand_2022['brand_share_pct'] = (
    decile_brand_2022['Tot_Clms'] /
    decile_brand_2022['decile_total'] * 100
).round(1)

# Step 1d: Pivot for readability
decile_pivot_2022 = decile_brand_2022.pivot(
    index='decile',
    columns='Brnd_Name',
    values='brand_share_pct'
).fillna(0)

# Reorder columns to match 2023 layout
decile_pivot_2022 = decile_pivot_2022[['Ozempic', 'Trulicity', 'Mounjaro', 'Rybelsus']]

print("BRAND SHARE WITHIN EACH DECILE — 2022")
print("=" * 65)
print(decile_pivot_2022.to_string())

BRAND SHARE WITHIN EACH DECILE — 2022
=================================================================
Brnd_Name  Ozempic  Trulicity  Mounjaro  Rybelsus
decile
1             35.0       58.0       0.2       6.8
2             35.2       60.0       0.1       4.7
3             33.5       62.2       0.1       4.2
4             33.7       61.8       0.1       4.4
5             35.3       59.0       0.2       5.5
6             36.2       58.4       0.2       5.2
7             36.8       57.2       0.2       5.8
8             37.9       55.3       0.3       6.5
9             38.5       54.4       0.4       6.7
10            41.7       51.3       0.8       6.1

In [43]:
# ─────────────────────────────────────────────────────────────
# YoY change in brand share within each decile
# ─────────────────────────────────────────────────────────────

# Combine the two pivots
yoy_change = decile_pivot - decile_pivot_2022

print("YOY CHANGE IN BRAND SHARE WITHIN EACH DECILE (2022 → 2023)")
print("=" * 70)
print(yoy_change.round(1).to_string())
print()
print("Positive number = brand gained share within that decile")
print("Negative number = brand lost share within that decile")

YOY CHANGE IN BRAND SHARE WITHIN EACH DECILE (2022 → 2023)
======================================================================
Brnd_Name  Ozempic  Trulicity  Mounjaro  Rybelsus
decile
1             14.7      -19.8       6.4      -1.3
2             19.9      -23.8       4.8      -0.9
3             21.9      -25.6       4.4      -0.8
4             19.0      -25.0       5.7       0.3
5             16.1      -21.8       6.4      -0.7
6             14.0      -21.2       7.3      -0.1
7             11.9      -20.1       8.4      -0.2
8              9.2      -18.3       9.8      -0.7
9              7.3      -18.3      11.5      -0.5
10             3.8      -16.8      13.4      -0.4

Positive number = brand gained share within that decile
Negative number = brand lost share within that decile

In [44]:
# ─────────────────────────────────────────────────────────────
# PRESSURE TEST 1: Sample size check
# Identify any specialty × decile cell with fewer than 100 prescribers
# ─────────────────────────────────────────────────────────────

# Recompute within-specialty prescriber counts (you've done this before)
top_5_specialties = [
    'Family Practice', 'Internal Medicine', 'Nurse Practitioner',
    'Endocrinology', 'Physician Assistant'
]

prescriber_with_specialty = df.groupby(
    ['Prscrbr_NPI', 'Prscrbr_Type']
)['Tot_Clms'].sum().reset_index()
prescriber_with_specialty.columns = ['Prscrbr_NPI', 'Specialty', 'total_glp1_claims']

prescriber_top5 = prescriber_with_specialty[
    prescriber_with_specialty['Specialty'].isin(top_5_specialties)
].copy()

prescriber_top5['within_specialty_decile'] = prescriber_top5.groupby(
    'Specialty'
)['total_glp1_claims'].transform(
    lambda x: pd.qcut(x, q=10, labels=range(1, 11), duplicates='drop')
)

# Count prescribers in each (specialty, decile) cell
sample_size_check = prescriber_top5.groupby(
    ['Specialty', 'within_specialty_decile'],
    observed=True
).size().reset_index(name='prescriber_count')

# Pivot for readability
sample_pivot = sample_size_check.pivot(
    index='within_specialty_decile',
    columns='Specialty',
    values='prescriber_count'
).fillna(0).astype(int)

# Reorder columns
sample_pivot = sample_pivot[top_5_specialties]

print("PRESCRIBER COUNT BY (SPECIALTY x WITHIN-SPECIALTY DECILE)")
print("=" * 70)
print(sample_pivot.to_string())

# Flag cells with <100 prescribers
print("\n" + "=" * 70)
print("CELLS WITH <100 PRESCRIBERS (potential sample size concerns)")
print("=" * 70)
small_cells = sample_pivot[sample_pivot < 100]
print(small_cells.fillna('OK').to_string())

PRESCRIBER COUNT BY (SPECIALTY x WITHIN-SPECIALTY DECILE)
======================================================================
Specialty                Family Practice  Internal Medicine  Nurse Practitioner  Endocrinology  Physician Assistant
within_specialty_decile
1                                   6518               4400                5490            575                 1718
2                                   4858               3985                3497            568                 1419
3                                   5516               3962                3811            573                 1239
4                                   5404               4047                4311            572                 1449
5                                   5513               3858                4023            568                 1352
6                                   5651               4028                3860            576                 1402
7                                   5501               3976                4215            570                 1409
8                                   5464               3930                4199            569                 1365
9                                   5492               4011                4111            568                 1409
10                                  5534               3988                4119            571                 1402

======================================================================
CELLS WITH <100 PRESCRIBERS (potential sample size concerns)
======================================================================
Specialty               Family Practice Internal Medicine Nurse Practitioner Endocrinology Physician Assistant
within_specialty_decile
1                                    OK                OK                 OK            OK                  OK
2                                    OK                OK                 OK            OK                  OK
3                                    OK                OK                 OK            OK                  OK
4                                    OK                OK                 OK            OK                  OK
5                                    OK                OK                 OK            OK                  OK
6                                    OK                OK                 OK            OK                  OK
7                                    OK                OK                 OK            OK                  OK
8                                    OK                OK                 OK            OK                  OK
9                                    OK                OK                 OK            OK                  OK
10                                   OK                OK                 OK            OK                  OK

In [45]:
# ─────────────────────────────────────────────────────────────
# PRESSURE TEST 2: Re-run YoY analysis with QUINTILES (5 buckets)
# Tests whether the split-pyramid pattern is bucketing-dependent
# ─────────────────────────────────────────────────────────────

# Step 1: Build quintiles for both years
prescriber_volume_2022_q = df_2022.groupby('Prscrbr_NPI')['Tot_Clms'].sum().reset_index()
prescriber_volume_2022_q.columns = ['Prscrbr_NPI', 'total_glp1_claims']
prescriber_volume_2022_q['quintile'] = pd.qcut(
    prescriber_volume_2022_q['total_glp1_claims'],
    q=5,
    labels=range(1, 6),
    duplicates='drop'
)

prescriber_volume_2023_q = df.groupby('Prscrbr_NPI')['Tot_Clms'].sum().reset_index()
prescriber_volume_2023_q.columns = ['Prscrbr_NPI', 'total_glp1_claims']
prescriber_volume_2023_q['quintile'] = pd.qcut(
    prescriber_volume_2023_q['total_glp1_claims'],
    q=5,
    labels=range(1, 6),
    duplicates='drop'
)

# Step 2: Merge quintile labels onto each year's data
df_2022_q = df_2022.merge(
    prescriber_volume_2022_q[['Prscrbr_NPI', 'quintile']],
    on='Prscrbr_NPI', how='left'
)
df_2023_q = df.merge(
    prescriber_volume_2023_q[['Prscrbr_NPI', 'quintile']],
    on='Prscrbr_NPI', how='left'
)

# Step 3: Brand share within each quintile, both years
def brand_share_by_quintile(dframe):
    grp = dframe.groupby(['quintile', 'Brnd_Name'], observed=True)['Tot_Clms'].sum().reset_index()
    grp['quintile_total'] = grp.groupby('quintile', observed=True)['Tot_Clms'].transform('sum')
    grp['share_pct'] = (grp['Tot_Clms'] / grp['quintile_total'] * 100).round(1)
    return grp.pivot(index='quintile', columns='Brnd_Name', values='share_pct').fillna(0)[
        ['Ozempic', 'Trulicity', 'Mounjaro', 'Rybelsus']
    ]

quintile_2022 = brand_share_by_quintile(df_2022_q)
quintile_2023 = brand_share_by_quintile(df_2023_q)

# Step 4: Compute YoY change at quintile level
quintile_change = quintile_2023 - quintile_2022

print("BRAND SHARE BY QUINTILE — 2022")
print("=" * 65)
print(quintile_2022.to_string())

print("\n" + "=" * 65)
print("BRAND SHARE BY QUINTILE — 2023")
print("=" * 65)
print(quintile_2023.to_string())

print("\n" + "=" * 65)
print("YoY CHANGE BY QUINTILE (2022 → 2023)")
print("=" * 65)
print(quintile_change.round(1).to_string())

BRAND SHARE BY QUINTILE — 2022
=================================================================
Brnd_Name  Ozempic  Trulicity  Mounjaro  Rybelsus
quintile
1             35.1       58.7       0.2       6.0
2             33.6       61.9       0.1       4.3
3             35.8       58.6       0.2       5.4
4             37.4       56.1       0.3       6.2
5             40.9       52.2       0.7       6.2

=================================================================
BRAND SHARE BY QUINTILE — 2023
=================================================================
Brnd_Name  Ozempic  Trulicity  Mounjaro  Rybelsus
quintile
1             52.8       37.1       5.6       4.5
2             53.9       36.7       5.2       4.1
3             50.7       37.2       7.1       5.0
4             47.7       37.0       9.5       5.7
5             45.6       35.0      13.6       5.9

=================================================================
YoY CHANGE BY QUINTILE (2022 → 2023)
=================================================================
Brnd_Name  Ozempic  Trulicity  Mounjaro  Rybelsus
quintile
1             17.7      -21.6       5.4      -1.5
2             20.3      -25.2       5.1      -0.2
3             14.9      -21.4       6.9      -0.4
4             10.3      -19.1       9.2      -0.5
5              4.7      -17.2      12.9      -0.3

In [46]:
# ─────────────────────────────────────────────────────────────
# PRESSURE TEST 3: Year-over-year stability of three-segment structure
# Recompute within-specialty decile structure for 2022, compare to 2023
# ─────────────────────────────────────────────────────────────

top_5_specialties = [
    'Family Practice', 'Internal Medicine', 'Nurse Practitioner',
    'Endocrinology', 'Physician Assistant'
]

def specialty_decile_structure(dframe, year_label):
    """Build within-specialty deciles and return summary stats per specialty"""
    
    # Get per-prescriber volume + specialty
    prescriber_with_specialty = dframe.groupby(
        ['Prscrbr_NPI', 'Prscrbr_Type']
    )['Tot_Clms'].sum().reset_index()
    prescriber_with_specialty.columns = ['Prscrbr_NPI', 'Specialty', 'total_glp1_claims']
    
    # Filter to top 5
    prescriber_top5 = prescriber_with_specialty[
        prescriber_with_specialty['Specialty'].isin(top_5_specialties)
    ].copy()
    
    # Build within-specialty deciles
    prescriber_top5['within_specialty_decile'] = prescriber_top5.groupby(
        'Specialty'
    )['total_glp1_claims'].transform(
        lambda x: pd.qcut(x, q=10, labels=range(1, 11), duplicates='drop')
    )
    
    # Build summary: for each specialty, what does Decile 10 look like?
    summary_rows = []
    for spec in top_5_specialties:
        spec_data = prescriber_top5[prescriber_top5['Specialty'] == spec]
        d10 = spec_data[spec_data['within_specialty_decile'] == 10]
        d1 = spec_data[spec_data['within_specialty_decile'] == 1]
        
        summary_rows.append({
            'Specialty': spec,
            'Year': year_label,
            'Total_prescribers': len(spec_data),
            'D10_avg_claims': round(d10['total_glp1_claims'].mean(), 1),
            'D10_max_claims': int(d10['total_glp1_claims'].max()) if len(d10) > 0 else 0,
            'D1_avg_claims': round(d1['total_glp1_claims'].mean(), 1),
            'D10_to_D1_ratio': round(d10['total_glp1_claims'].mean() / d1['total_glp1_claims'].mean(), 1) if len(d1) > 0 and d1['total_glp1_claims'].mean() > 0 else 0
        })
    
    return pd.DataFrame(summary_rows)

# Run for both years
struct_2022 = specialty_decile_structure(df_2022, '2022')
struct_2023 = specialty_decile_structure(df, '2023')

print("WITHIN-SPECIALTY DECILE STRUCTURE — 2022")
print("=" * 75)
print(struct_2022.to_string(index=False))

print("\n" + "=" * 75)
print("WITHIN-SPECIALTY DECILE STRUCTURE — 2023")
print("=" * 75)
print(struct_2023.to_string(index=False))

# Compute the change in volume gap
print("\n" + "=" * 75)
print("YoY STABILITY CHECK: D10_avg_claims by specialty")
print("=" * 75)
comparison = pd.merge(
    struct_2022[['Specialty', 'D10_avg_claims']].rename(columns={'D10_avg_claims': 'D10_2022'}),
    struct_2023[['Specialty', 'D10_avg_claims']].rename(columns={'D10_avg_claims': 'D10_2023'}),
    on='Specialty'
)
comparison['change_pct'] = ((comparison['D10_2023'] - comparison['D10_2022']) / comparison['D10_2022'] * 100).round(1)
print(comparison.to_string(index=False))

WITHIN-SPECIALTY DECILE STRUCTURE — 2022
===========================================================================
          Specialty Year  Total_prescribers  D10_avg_claims  D10_max_claims  D1_avg_claims  D10_to_D1_ratio
    Family Practice 2022              42114           166.1            1090           12.0             13.9
  Internal Medicine 2022              31364           227.1            4565           12.0             19.0
 Nurse Practitioner 2022              27187           232.6            2229           11.5             20.2
      Endocrinology 2022               5417           784.4            4612           22.8             34.4
Physician Assistant 2022               9915           211.3            1356           11.5             18.4

===========================================================================
WITHIN-SPECIALTY DECILE STRUCTURE — 2023
===========================================================================
          Specialty Year  Total_prescribers  D10_avg_claims  D10_max_claims  D1_avg_claims  D10_to_D1_ratio
    Family Practice 2023              55451           236.6            1311           12.3             19.2
  Internal Medicine 2023              40185           315.2            5832           12.4             25.5
 Nurse Practitioner 2023              41636           282.4            1876           11.9             23.7
      Endocrinology 2023               5710          1036.2            6704           25.8             40.2
Physician Assistant 2023              14164           267.8            1963           11.9             22.5

===========================================================================
YoY STABILITY CHECK: D10_avg_claims by specialty
===========================================================================
          Specialty  D10_2022  D10_2023  change_pct
    Family Practice     166.1     236.6        42.4
  Internal Medicine     227.1     315.2        38.8
 Nurse Practitioner     232.6     282.4        21.4
      Endocrinology     784.4    1036.2        32.1
Physician Assistant     211.3     267.8        26.7

In [47]:
# ─────────────────────────────────────────────────────────────
# WHY-DRILL TEST: Hypothesis A — Clinical Evidence
# Question: Is Lilly's Decile 10 strength concentrated in endocrinology
# specifically, or spread across all specialties?
# ─────────────────────────────────────────────────────────────

# Step 1: Build (specialty, all-population decile, company) share table for 2023
# We use ALL-POPULATION deciles (not within-specialty) because the original
# split-pyramid finding was at the all-population decile level.

# Get decile labels onto the 2023 dataframe (you have this — df_2023_d)
# We need to also tag company

def assign_company(brand):
    if brand in ['Ozempic', 'Rybelsus']:
        return 'Novo'
    elif brand in ['Trulicity', 'Mounjaro']:
        return 'Lilly'
    return 'Other'

df_2023_d['Company'] = df_2023_d['Brnd_Name'].apply(assign_company)

# Top 5 specialties (96% of volume)
top_5_specialties = [
    'Family Practice', 'Internal Medicine', 'Nurse Practitioner',
    'Endocrinology', 'Physician Assistant'
]

# Filter to top 5 specialties
df_top5_2023 = df_2023_d[df_2023_d['Prscrbr_Type'].isin(top_5_specialties)].copy()

# Step 2: For each (specialty, decile), compute Novo vs Lilly share
specialty_decile_company = df_top5_2023.groupby(
    ['Prscrbr_Type', 'decile', 'Company'],
    observed=True
)['Tot_Clms'].sum().reset_index()

# Pivot to get Novo and Lilly side by side
specialty_decile_pivot = specialty_decile_company.pivot_table(
    index=['Prscrbr_Type', 'decile'],
    columns='Company',
    values='Tot_Clms',
    fill_value=0
).reset_index()

# Calculate Novo share within each (specialty, decile) cell
specialty_decile_pivot['novo_share_pct'] = (
    specialty_decile_pivot['Novo'] /
    (specialty_decile_pivot['Novo'] + specialty_decile_pivot['Lilly']) * 100
).round(1)

# Step 3: Pivot for readability — specialties as columns, deciles as rows
result = specialty_decile_pivot.pivot(
    index='decile',
    columns='Prscrbr_Type',
    values='novo_share_pct'
).fillna(0)

# Reorder columns
result = result[top_5_specialties]

print("NOVO SHARE BY (SPECIALTY x DECILE) — 2023")
print("=" * 80)
print(result.to_string())

# Step 4: Highlight Decile 10 specifically
print("\n" + "=" * 80)
print("DECILE 10 NOVO SHARE BY SPECIALTY")
print("=" * 80)
decile_10_view = result.loc[10].sort_values()
print(decile_10_view.to_string())

NOVO SHARE BY (SPECIALTY x DECILE) — 2023
================================================================================
Prscrbr_Type  Family Practice  Internal Medicine  Nurse Practitioner  Endocrinology  Physician Assistant
decile
1                        55.7               57.3                53.6           65.6                 55.6
2                        59.4               60.7                57.2           71.1                 59.0
3                        58.5               60.3                57.6           62.9                 60.0
4                        57.0               58.6                56.7           63.2                 55.4
5                        56.2               58.4                54.1           55.7                 55.8
6                        55.0               57.2                53.7           52.9                 54.7
7                        53.6               55.8                53.2           54.5                 53.4
8                        52.7               54.1                51.6           52.6                 51.1
9                        51.7               52.7                51.0           50.2                 52.4
10                       50.7               52.4                49.8           51.0                 51.5

================================================================================
DECILE 10 NOVO SHARE BY SPECIALTY
================================================================================
Prscrbr_Type
Nurse Practitioner     49.8
Family Practice        50.7
Endocrinology          51.0
Physician Assistant    51.5
Internal Medicine      52.4

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_21284\3797151343.py:39: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  specialty_decile_pivot = specialty_decile_company.pivot_table(